#BSUB -q gpu
#BSUB -J MPI_CUDA
#BSUB -L /bin/bash
#BSUB -o %J.out
#BSUB -e %J.err
#BSUB -n 16
#BSUB -R "span[ptile=16]"

MODULEPATH=/lustre/utility/modulefiles:$MODULEPATH
module purge && module load cuda/5.5

./cuda md5 4096 524288 cuda
./generator md5 test
./crack md5 file md5_4096-524288_cuda Test.txt

#./cuda des 4096 524288 cuda
#./cuda md5 4096 524288 cuda
#./cuda sha1 4096 524288 cuda
#./cuda hmac 4096 524288 cuda
